package mhf.dao.impl;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;

import mhf.bean.Game;
import mhf.dao.GameDAO;

public class GameDAOImpl extends SqlMapClientDaoSupport implements GameDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */



	/**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public void insert(Game record) {
        getSqlMapClientTemplate().insert("game.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public int updateByPrimaryKey(Game record) {
        int rows = getSqlMapClientTemplate().update("game.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public int updateByPrimaryKeySelective(Game record) {
        int rows = getSqlMapClientTemplate().update("game.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public Game selectByPrimaryKey(Integer level) {
        Game key = new Game();
        key.setLevel(level);
        Game record = (Game) getSqlMapClientTemplate().queryForObject("game.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public int deleteByPrimaryKey(Integer level) {
        Game key = new Game();
        key.setLevel(level);
        int rows = getSqlMapClientTemplate().delete("game.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

	@Override
	public int selectPrizeByLevel(Integer level) {
		System.out.println(level+"dao");
		return (Integer) getSqlMapClientTemplate().queryForObject("game.selectPrizeByLevel",level);
	}
}