package mhf.dao;

import mhf.bean.Game;

public interface GameDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    void insert(Game record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    int updateByPrimaryKey(Game record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    int updateByPrimaryKeySelective(Game record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    Game selectByPrimaryKey(Integer level);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table game
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    int deleteByPrimaryKey(Integer level);
    
    int selectPrizeByLevel(Integer level);
}