package mhf.bean;

public class Game {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game.level
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game.prize
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    private Integer prize;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game.level
     *
     * @return the value of game.level
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game.level
     *
     * @param level the value for game.level
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game.prize
     *
     * @return the value of game.prize
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public Integer getPrize() {
        return prize;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game.prize
     *
     * @param prize the value for game.prize
     *
     * @abatorgenerated Tue Dec 15 11:25:21 CST 2015
     */
    public void setPrize(Integer prize) {
        this.prize = prize;
    }
}